[technote]
id = "RTN-101"
series_id = "RTN"
canonical_url = "https://rtn-101.lsst.io"
github_url = "https://github.com/lsst/rtn-101"
github_default_branch = "main"
date_created = 2025-06-17T12:38:31Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Fabio"
name.family = "Hernandez"
internal_id = "hernandezf"
orcid = "https://orcid.org/0000-0001-7203-2552"
[[technote.authors.affiliations]]
name = "CNRS"
internal_id = "Lyon-CC-IN2P3"
address = "CC-IN2P3, 21 avenue Pierre de Coubertin, CS70202, F-69627 Villeurbanne cedex, France"
[[technote.authors]]
name = {given = "Quentin", family = "Le Boulc'h"}
internal_id = "leboulchq"
[[technote.authors.affiliations]]
name = "CNRS"
internal_id = "Lyon-CC-IN2P3"
address = "CC-IN2P3, 21 avenue Pierre de Coubertin, CS70202, F-69627 Villeurbanne cedex, France"
